# permissions for end users to view minioserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: minioserviceaccount-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: labels
    app.kubernetes.io/part-of: labels
    app.kubernetes.io/managed-by: kustomize
  name: minioserviceaccount-viewer-role
rules:
- apiGroups:
  - infra.d464.sh
  resources:
  - minioserviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.d464.sh
  resources:
  - minioserviceaccounts/status
  verbs:
  - get
