---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - domainnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.d464.sh
  resources:
  - domainnames/finalizers
  verbs:
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - domainnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - minioserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.d464.sh
  resources:
  - minioserviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - minioserviceaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - portforwards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.d464.sh
  resources:
  - portforwards/finalizers
  verbs:
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - portforwards/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.d464.sh
  resources:
  - postgres/finalizers
  verbs:
  - update
- apiGroups:
  - infra.d464.sh
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
